
name: CI
env:
  NODE_VERSION: '10.x'   # set this to the node version to use

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 9 * * *'
    - cron:  '15 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: Master
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      run: |
        npm ci

    - name: Book Tee Times
      run: |
        npx cypress run --spec "cypress/integration/specs/bookTeeTime.spec.ts" --env account_email=${{ secrets.CHRONOGOLF_EMAIL }},account_password=${{ secrets.CHRONOGOLF_PASSWORD }}
    